---
apiVersion: v1
kind: Namespace
metadata:
  name: metal-test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: http
  namespace: metal-test
  labels:
    app: nginx
spec:
  serviceName: "nginx"
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: registrycred
      containers:
      - name: nginx
        image: gldreg.orangesv.us/jeremy.huylebroeck/registry-test/simple-http:latest
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: metal-test
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

# kubectl create secret docker-registry regcred 
# --docker-server=<your-registry-server> 
# --docker-username=<your-name> 
# --docker-password=<your-pword>  # THIS CAN BE A TOKEN WITH READ ONLY ACCESS ON THE REGISTRY
# --docker-email=<your-email>

# kubectl create secret docker-registry registrycred \
# --docker-server=gldreg.orangesv.us \
# --docker-username=jeremy.huylebroeck \
# --docker-password=ovkVywT-cgJtsJssMxov \
# --docker-email=jeremy.huylebroeck@orange.com


# # kubectl get secret registrycred --output="jsonpath={.data.\.dockerconfigjson}" | base64 -D
# kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" | base64 -D